# set -ex

# CPU_ARCHITECTURE=""
# if [[ `uname -a` =~ ^Darwin.* ]] && [[ `uname -a` =~ .*arm64$ ]]
# then
#     CPU_ARCHITECTURE="ARM64"
#     CMAKE_MORE_OPTIONS="${CMAKE_MORE_OPTIONS} -DBUILD_SSE2_CODEPATHS=OFF"
# else
# 	CPU_ARCHITECTURE="Intel"
# fi;

# mkdir build
cd build

cmake .. \
    -G $GENERATOR \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX"\
    -DCMAKE_BUILD_TYPE=Release \
    -DRAWSPEED_ENABLE_LTO=ON \
    -DBUILD_CURVE_TOOLS=OFF \
    -DBUILD_NOISE_TOOLS=OFF \
    -DUSE_LUA=OFF \
    -DUSE_BUNDLED_LUA=OFF \
    -DUSE_LIBRAW=ON \
    -DUSE_BUNDLED_LIBRAW=OFF \
    -DUSE_GRAPHICSMAGICK=ON \
    -DUSE_IMAGEMAGICK=OFF \
    -DBUILD_SSE2_CODEPATHS=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DUSE_COLORD=OFF \
    -DUSE_KWALLET=OFF \
    -DBUILD_CMSTEST=OFF \
    -DBUILD_BENCHMARKING=OFF \
    -DBINARY_PACKAGE_BUILD=OFF 

cmake --build . --target install



